version: '2'
services:
  nginx:
    build:
      context: ./containers/nginx/
    ports:
      - "82:80"
    volumes:
      - ./logs:/etc/logs/nginx
      - ./containers/nginx/conf:/etc/nginx/conf.d/
    volumes_from:
      - fpm:rw
    links:
      - fpm

  fpm:
    build:
      context: ./containers/fpm/
    volumes:
      - ./task-code:/var/www:rw
    links:
      - postgres

  postgres:
    build:
      context: ./containers/postgres/
    ports:
      - "5435:5432"
    volumes:
      - ./database/postgres:/data/postgres

